#!/usr/bin/env python3
"""Emit a 256-entry signed sine table as z80asm `db` lines (sintab.inc).

sintab[i] = round(118 * sin(2*pi*i/256)), stored as a two's-complement byte.
Amplitude 118 keeps values in signed-8 range (-118..118) with headroom so the
field sum (two lookups + drift) stays well-behaved, and gives a ~1.8px step
in 6.10-ish fixed point. cos(a) is just sintab[(a+64)&255]."""
import math

with open("sintab.inc", "w") as f:
    f.write("; auto-generated by gen_sintab.py — 256-entry signed sine table\n")
    f.write("sintab:\n")
    vals = [round(118 * math.sin(2 * math.pi * i / 256)) & 0xFF for i in range(256)]
    for r in range(0, 256, 8):
        row = ",".join(f"0%02xh" % v for v in vals[r:r + 8])
        f.write(f"        db {row}\n")
print("wrote sintab.inc (256 bytes)")
